In [2]:
import numpy as np

Here are some basic operations on matrices in Numpy. First, generate a randome matrix

In [3]:
matX = np.arange(60).reshape(6,10)
print (matX)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [4]:
# Print the diagonal, upper triangle and lower triangle of matrix X
print(np.diag(matX))
print(np.triu(matX))
print(np.tril(matX))

[ 0 11 22 33 44 55]
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 0 11 12 13 14 15 16 17 18 19]
 [ 0  0 22 23 24 25 26 27 28 29]
 [ 0  0  0 33 34 35 36 37 38 39]
 [ 0  0  0  0 44 45 46 47 48 49]
 [ 0  0  0  0  0 55 56 57 58 59]]
[[ 0  0  0  0  0  0  0  0  0  0]
 [10 11  0  0  0  0  0  0  0  0]
 [20 21 22  0  0  0  0  0  0  0]
 [30 31 32 33  0  0  0  0  0  0]
 [40 41 42 43 44  0  0  0  0  0]
 [50 51 52 53 54 55  0  0  0  0]]


We can also compute the matrix products of two matrices

In [6]:
mat1 = np.array([[2, 3, 4],[1, 2, 4]])
print(mat1)
mat2 = np.array([[0, -1],[3, -4],[1, 2]])
print(mat2)

[[2 3 4]
 [1 2 4]]
[[ 0 -1]
 [ 3 -4]
 [ 1  2]]


In [8]:
print(mat1 @ mat2)

[[13 -6]
 [10 -1]]


Here is the transpose

In [10]:
mat1_T = mat1.T
print(mat1_T)

[[2 1]
 [3 2]
 [4 4]]


And the determinant...

In [12]:
matA = np.array([[-1, 3],[1, -1]])

print(np.linalg.det(matA))

-2.0


And the inverse of a matrix, just like the example in class.

In [13]:
matA_inv = np.linalg.inv(matA)
print(matA_inv)

[[0.5 1.5]
 [0.5 0.5]]


Housing Data Example

In [13]:
# Enter the Housing Data matrices

A = np.array([[1, 1500, 3],
              [1, 2000, 4],
              [1, 1800, 3]])
B = np.array([300000, 400000, 330000]).T
x = np.linalg.inv(A)@B
print(x)

[    0.   100. 50000.]


In [15]:
# And again with the expanded Housing Data matrices

A1 = np.array([[1, 1500, 3],
               [1, 2000, 4],
               [1, 1800, 3],
               [1, 2200, 4],
               [1, 1600, 3],
               [1, 2400, 5],
               [1, 1700, 3]])
B1 = np.array([[300000],
               [400000],
               [330000],
               [440000],
               [310000],
               [480000],
               [320000]])
D = np.linalg.pinv(A1) @ B1
print(D)

[[-14400.]
 [   144.]
 [ 31200.]]


In [18]:
estimated_prices = A1 @ D
print(estimated_prices)

[[295200.]
 [398400.]
 [338400.]
 [427200.]
 [309600.]
 [487200.]
 [324000.]]


Note that the estimated prices do not exactly match the input prices we have in matrix B1! This is because we've essentially solved for a regression line through the points!