In [3]:
asList = [1, 2, 3]

In [4]:
print(asList)

[1, 2, 3]


In [5]:
import numpy as np


In [7]:
rowVec = np.array([[1,2,3]])
print(rowVec)

[[1 2 3]]


In [8]:
colVec = np.array([[1],[2],[3]])
print(colVec)

[[1]
 [2]
 [3]]


In [9]:
matrix1 = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(matrix1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [10]:
Vec1 = np.array([[3],[7],[0],[1]])
Vec2 = np.array([[1],[2],[4],[1]])
Vec1+Vec2

array([[4],
       [9],
       [4],
       [2]])

In [11]:
Vec3 = np.array([[1,2,4,1]])

In [12]:
Vec1+Vec3

array([[ 4,  5,  7,  4],
       [ 8,  9, 11,  8],
       [ 1,  2,  4,  1],
       [ 2,  3,  5,  2]])

In [13]:
Vec4 = np.array([[1],[2],[4]])
Vec1+Vec4

ValueError: operands could not be broadcast together with shapes (4,1) (3,1) 

In [15]:
# Dot Products and Norms

In [17]:
vec = np.array([1,2,3,4,5,6])
vec_mag = np.linalg.norm(vec)
print(vec_mag)

9.539392014169456


In [19]:
vec1 = np.array([5,0])
vec2 = np.array([2,4])
dot_prod = np.dot(vec1,vec2)
print(dot_prod)

10


In [20]:
angle = np.arccos(dot_prod/(np.linalg.norm(vec1)*np.linalg.norm(vec2)))
print(np.degrees(angle))

63.43494882292201


In [21]:
math = np.array([87, 64, 94, 45, 76])
science = np.array([99, 84, 82, 58, 79])

In [22]:
x = math - np.mean(math)
y = science - np.mean(science)

In [23]:
correlation = np.dot(x,y)/(np.sqrt(np.dot(x, x))*np.sqrt(np.dot(y,y)))
print(correlation)

0.7737224379366526


In [24]:
print(np.corrcoef(math, science))

[[1.         0.77372244]
 [0.77372244 1.        ]]
