Eigendecomposition

Start with an example 2x2 matrix and perform an eigendecomposition. 

In [20]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [5]:
A = np.array([[4,1],[2,3]])
print(A)

[[4 1]
 [2 3]]


In [6]:
# Print out the results of numpy's eigenvalue/eigenvector calcuation directly to see its format

print(np.linalg.eig(A))

(array([5., 2.]), array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]]))


In [7]:
# Two arrays are apparent. The first array contains the eigenvalues. The second array contains the eigenvector matrix. 
# REMEMBER: THE EIGENVECTORS ARE THE COLUMNS OF THE EIGENVECTOR MATRIX!!

evals = np.linalg.eig(A)[0]
evecs = np.linalg.eig(A)[1]

print(evals)
print(evecs)

[5. 2.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


Also remember, there are infinitely many scaled solutions of the characteristic equation for each eigenvector. Numpy returns unit-normalized eigenvectors, that is, a nominal eigenvector divided by its L2 norm (Euclidean). 

In [10]:
# Verify that the eigendecomposition returns the original matrix

L = np.diag(evals)
V = evecs

A_new = V @ L @ np.linalg.inv(V)
print(A_new)

[[4. 1.]
 [2. 3.]]


Here we implement a basic singular value decomposition on a sample matrix.

In [18]:
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print("Original matrix B: \n", B)

Original matrix B: 
 [[1 2]
 [3 4]
 [5 6]]


In [21]:
U, S, V_T = np.linalg.svd(B, full_matrices=True)
print("Matrix U (Left singular vectors): \n", U)
print("Diagonal Matrix Sigma (Singular values): \n", S)
print("Matrix V-transpose (Transposed right singular vectors): \n", V_T)

Matrix U (Left singular vectors): 
 [[-0.23  0.88  0.41]
 [-0.52  0.24 -0.82]
 [-0.82 -0.4   0.41]]
Diagonal Matrix Sigma (Singular values): 
 [9.53 0.51]
Matrix V-transpose (Transposed right singular vectors): 
 [[-0.62 -0.78]
 [-0.78  0.62]]


NOTE: Using SVD in Numpy has a few features to note:
1) The singular values, S, are returned as a vector not a diagonal matrix. You can make a diagonal matrix using the code below.
2) The right-singular vectors are returned in the transposed matrix, V-transpose. To get actual V, you must transpose again.

In [22]:
Sigma = np.zeros(np.shape(B))
np.fill_diagonal(Sigma, S)
print("Diagonal Matrix Sigma (Singular values): \n", Sigma)

V = V_T.T
print("Matrix V (Right singular vectors): \n", V)

Diagonal Matrix Sigma (Singular values): 
 [[9.53 0.  ]
 [0.   0.51]
 [0.   0.  ]]
Matrix V (Right singular vectors): 
 [[-0.62 -0.78]
 [-0.78  0.62]]


In [23]:
# Verify that we can return the original matrix B using the SVD components

B_reconstructed = U @ Sigma @ V_T
print("Matrix B reconstructed: \n", B_reconstructed)

Matrix B reconstructed: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [29]:
# Remember the eigenvectors of AA_T are the left-singular vectors and those of A_TA are the right-singular vectors.
U_eig = np.linalg.eig(B @ B.T)[1]
print(U_eig)

# Remember the rows of V are the singular vectors, but the columns of the eigendecomposition are the vectors.
# Each column of the eigenvectors corresponds to each row of the right-singular vectors.
V_eig = np.linalg.eig(B.T @ B)[1]
print(V_eig)

[[-0.23 -0.88  0.41]
 [-0.52 -0.24 -0.82]
 [-0.82  0.4   0.41]]
[[-0.78 -0.62]
 [ 0.62 -0.78]]


In [31]:
# Finally, the square root of the eigenvalues equals the singular values.

S_eig = np.sqrt(np.linalg.eig(B.T @ B)[0])
print(S_eig)

[0.51 9.53]
